---
title: "Figures"
author: "Summer Heschong"
date: "2025-03-05"
output: html_document
---
#Setup 
```{r setup}
library(here)
library(dplyr)
library(tidyverse)
library(ggplot2)

#load data
wetland_data <- read.csv(here('Data/Processed/WQ-Data-NCDWR-2005-to-2015-NCSU-2015-to-2019.csv'))

```

#Inspect and Wrangle data
```{r wrangle}

#I tried to make some graphs and I think there might not be enough data for sites 1014 and 1018

#filter for just NWCA project sites
NWCA <- wetland_data %>%
  filter(Project == 'NWCA Intensification')

#see which sites in the NWCA project have the most observations
sort(table(NWCA$Site), decreasing = TRUE)

#lets try 1161 and 1012 instead? 

#ok we might have to pick sites that aren't in the NWCA project. There's a lot less data than it seems because all the water quality parameters are grouped in one column

#which sites overall have the most observations?
sort(table(wetland_data$Site), decreasing = TRUE)

#Hog Farm Upper, Walmart, and Nahunta are all in project Headwater and they have up and downstream data

#create a dataset for each site
HogFarm <- wetland_data %>%
  filter(Site == 'Hog Farm Upper')

Walmart <- wetland_data %>%
  filter(Site == 'Walmart')

Nahunta <- wetland_data %>%
  filter(Site == 'Nahunta')

#create a dataset with just our sites
Project_sites <- wetland_data %>%
  filter(Site %in% c('Hog Farm Upper', 'Walmart', 'Nahunta'))
```

#Visualize data
##Water quality upstream vs downstream
```{r visualize up and dwn}
#Compare water quality parameters upstream and downstream for same site

#First filter dataset for one parameter
HogFarm_pH <- HogFarm %>%
  filter(Parameter == 'pH')

#create histograms of parameter by location
HogFarm_pH_hist <- ggplot(HogFarm_pH, aes(x = Result, fill = Location.Type)) +
  geom_histogram(bins = 6, binwidth = 0.2, color = 'black') +
  facet_wrap(~Location.Type)

HogFarm_pH_hist

#create scatterplot of parameter by location
HogFarm_ph_scatter <- ggplot(HogFarm_pH, aes(x = Location.Type, y = Result)) +
  geom_point(size = 3, alpha = 0.5)

HogFarm_ph_scatter

#Should we combine Downstream and Further Downstream?
```

## Metal Concentrations and pH
```{r visualize metal}
#first filter data for pH and copper (can change for other metals) and separate them into 2 columns

metal_vs_pH <- Project_sites %>%
  select(Station.Name, Parameter, Result) %>%
  filter(Parameter == 'Copper' | Parameter == 'pH') %>%
  pivot_wider(names_from = Parameter, values_from = Result, values_fn = mean)
#there were duplicate values when i first did pivot_wider so i used the mean of the duplicates. Idk how much this matters statistically? 

#create a scatterplot to examine relationship between metal concentrations and pH
ggplot(metal_vs_pH, aes(x = pH, y = Copper)) +
  geom_point() +
  geom_smooth(method = lm)

#I don't think this plot really works?
```


