---
title: "New Data Cleaning_NG"
output: html_document
---

```{r}
library(here)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(moments)
library(readxl)
library(lubridate)

```


```{r}

YSI_2012_2015_1 <- read_excel('Data/Raw/SWAMP YSI-compiled-2012-2015.xlsx')

YSI_2015_2025_1 <- read_excel('Data/Raw/SWAMP YSI-compiled-2015-2025.xlsx')

Nutrients_2011_2025_1 <- read.csv('Data/Raw/Nutrients2011_2025-summary.csv')

```

## YSI 2015-2025

```{r}

#Selecting the columns I want

YSI_2015_2025_2 <- YSI_2015_2025_1 %>% 
  select("Date", "Site", "Temperature, C",
         "Dissolved O2, %", "Dissolved O2, mg/L", 
         "Sp. Conductivity, uS/cm at 25C", "Conductivity, uS/cm", 
         "TDS, mg/L", "Salinity, ‰", "pH" )

#converting all measurements to numeric value

YSI_2015_2025_3 <- YSI_2015_2025_2 %>% 
  mutate(across(c("Temperature, C",
         "Dissolved O2, %", "Dissolved O2, mg/L", 
         "Sp. Conductivity, uS/cm at 25C", "Conductivity, uS/cm", 
         "TDS, mg/L", "Salinity, ‰", "pH" ), as.numeric))

#converting dates to date format

YSI_2015_2025_4  <- YSI_2015_2025_3 %>%
  mutate(Date = ymd(Date),
         Month = month(Date),
         Year = year(Date)) 


YSI_2015_2025_5 <- YSI_2015_2025_4 %>% 
  rename(Date = Date, 
         Site = Site, 
         Temp_C = "Temperature, C", 
         SpCond_mScm = "Sp. Conductivity, uS/cm at 25C", 
         Cond_mScm = "Conductivity, uS/cm", 
         TDS_mgl = "TDS, mg/L",   
         Sal_ppt = "Salinity, ‰", 
         DO_percent = "Dissolved O2, %", 
         DO_mgL = "Dissolved O2, mg/L", 
         pH = "pH", 
         Month = Month, 
         Year = Year)

YSI_2015_2025_6 <- YSI_2015_2025_5 %>%
  mutate(SpCond_mScm = SpCond_mScm/1000,
         Cond_mScm = Cond_mScm/1000) %>% 
  mutate(Season = case_when(
    Month %in% c(12, 1, 2) ~ "Winter",
    Month %in% c(3, 4, 5)  ~ "Spring",
    Month %in% c(6, 7, 8)  ~ "Summer",
    Month %in% c(9, 10, 11) ~ "Fall"
  ))
  
```


## YSI 2012-2015

```{r}

#Selecting the columns I want

YSI_2012_2015_2 <- YSI_2012_2015_1 %>% 
  select("Date", "Site", "Temp C", "SpCond mS/cm", 
         "Cond mS/cm", "TDS mg/L", "Salinity ppt", 
         "DO %", "DO mg/L", "pH")

#converting all measurements to numeric value

YSI_2012_2015_3 <- YSI_2012_2015_2 %>% 
  mutate(across(c("Temp C","SpCond mS/cm","Cond mS/cm", 
                  "TDS mg/L", "Salinity ppt", 
                  "DO %","DO mg/L", "pH"), as.numeric))

#converting dates to date format

YSI_2012_2015_4 <- YSI_2012_2015_3 %>% 
  mutate(Date = ymd(Date),
         Month = month(Date),
         Year = year(Date))

#changing column names for consistency

YSI_2012_2015_5 <- YSI_2012_2015_4 %>% 
  rename(Date = Date, 
         Site = Site, 
         Temp_C = "Temp C" , 
         SpCond_mScm = "SpCond mS/cm", 
         Cond_mScm = "Cond mS/cm", 
         TDS_mgl = "TDS mg/L"  ,   
         Sal_ppt = "Salinity ppt" , 
         DO_percent = "DO %" , 
         DO_mgL = "DO mg/L", 
         pH = "pH", 
         Month = Month, 
         Year = Year)

YSI_2012_2015_6 <- YSI_2012_2015_5 %>%
  mutate(Season = case_when(
    Month %in% c(12, 1, 2) ~ "Winter",
    Month %in% c(3, 4, 5)  ~ "Spring",
    Month %in% c(6, 7, 8)  ~ "Summer",
    Month %in% c(9, 10, 11) ~ "Fall"
  ))

```

## Combined Dataset

```{r}

YSI_Combined <- bind_rows(YSI_2012_2015_6, YSI_2015_2025_6)

#write.csv(YSI_Combined, "Data/Processed/YSI_Combined.csv", row.names = FALSE)
```

## Nutrients Dataset

```{r}

Nutrients_2011_2025_2 <- Nutrients_2011_2025_1 %>% 
 mutate(across(c("Unfiltered_TN_ugL","Filtered_NOx_ugL","Filtered_NHx_ugL", 
                 "Unfiltered_TP_.ugL","Filtered_OP_ugL","TSS_mgL",
                 "fecal_coliform_colonies_per100mL"), as.numeric)) %>%
  rename(tracking_no = "Tracking.No.", 
         Date = "Date", 
         Site = "Site",
         Rep = "Rep",
         Unfiltered_TN_ugL = "Unfiltered_TN_ugL",
         Filtered_NOx_ugL = "Filtered_NOx_ugL",
         Filtered_NHx_ugL = "Filtered_NHx_ugL",
         Unfiltered_TP_ugL = "Unfiltered_TP_.ugL",
         Filtered_OP_ugL = "Filtered_OP_ugL",
         TSS_mgL = "TSS_mgL", 
         fecal_coliform_colonies_per100mL = "fecal_coliform_colonies_per100mL") %>% 
  mutate(Date = mdy(Date))

Nutrients_2011_2025_3 <- Nutrients_2011_2025_2 %>% 
  group_by(Site, Date) %>% 
  summarise(across(where(is.numeric), mean, na.rm = T), .groups = "drop")
  

  
```


## Prep to combine the data
```{r}

YSI_Combined <- YSI_Combined %>%
  mutate(Site = gsub("-", "", Site))

common_sites <- intersect(unique(YSI_Combined$Site), unique(Nutrients_2011_2025_3$Site))
print(common_sites)

YSI_Combined <- YSI_Combined %>%
  filter(Site %in% common_sites)

Nutrients_2011_2025_3 <- Nutrients_2011_2025_3 %>%
  filter(Site %in% common_sites)



```

## Combined Data Final???

```{r}

Combined_Data <- full_join(YSI_Combined, Nutrients_2011_2025_3, by = c("Site", "Date"))

Combined_Data <- Combined_Data %>%
  select(-Rep) %>%  
  mutate_if(is.numeric, ~ ifelse(is.nan(.), NA, .))

#write.csv(Combined_Data, "Data/Processed/Combined_Data.csv", row.names = FALSE)

data <- read.csv("Data/Processed/Combined_Data.csv")

Combined_Data_NArm <- data %>% 
  drop_na()

#write.csv(Combined_Data_NArm, "Data/Processed/Combined_Data_NArm.csv", row.names = FALSE)


Combined_Data_NArm %>%
  count(Site) %>%
  print()
```



## next steps - organize the nutrients data
## YSI - average by month/ site
## convert dates to month/ year format and merge with nutrient columns
## create a season column
## leave regular month column

