---
title: "TotalN_Models"
author: "Aidan Power"
date: "2025-04-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Packages and Import Dataset

```{r Load Packages}
library(here)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(moments)
library(readxl)
library(lubridate)

```

```{r Import Daraset}

Combined_Data <- read.csv("Data/Processed/Combined_Data.csv")

YSI_Combined <- read.csv("Data/Processed/YSI_Combined.csv")

NA_Combined <- read.csv("Data/Processed/Combined_Data_NArm.csv")

Log_Combined <- read.csv("Data/Processed/Log_Transformed_Data.csv")

```

Predictor variables: Temperature, Specific Conductivity, Conductivity, TDS, Salinity, DO, pH, season, TSS

#Outliers

```{r Remove Outliers}

NA_Combined <- NA_Combined %>%
  mutate(across(where(is.numeric), 
                ~ ifelse(abs
                         (. - mean
                         (., na.rm = TRUE)) > 3 * sd
                         (., na.rm = TRUE), NA, .)))

Log_Combined <- Log_Combined %>%
  mutate(across(where(is.numeric), 
                ~ ifelse(abs
                         (. - mean
                         (., na.rm = TRUE)) > 3 * sd
                         (., na.rm = TRUE), NA, .))) 


```



#Data Interpretation

```{r Raw Distributions}

ggplot(NA_Combined, aes(x = Temp_C)) +
geom_histogram() #Are we showing the histograms? Do we need Rice's rule?
#Bimodal

ggplot(Log_Combined, aes(x = log10(Temp_C))) +
geom_histogram()
#Negatively skewed, I am against using this


#Specific Conductivity
ggplot(NA_Combined, aes(x = SpCond_mScm)) +
geom_histogram() 

skewness(NA_Combined$SpCond_mScm)
kurtosis(NA_Combined$SpCond_mScm) #These both show NA, going to try log transforming

ggplot(Log_Combined, aes(x = Log_SpCond_mScm)) +
geom_histogram()

skewness(Log_Combined$Log_SpCond_mScm) #Still returning NA


#Conductivity
ggplot(NA_Combined, aes(x = Cond_mScm)) +
geom_histogram() #Positively skewed

ggplot(Log_Combined, aes(x = Log_Cond_mScm)) +
geom_histogram()

#TDS
ggplot(NA_Combined, aes(x = TDS_mgl)) +
geom_histogram() 

ggplot(Log_Combined, aes(x = Log_TDS_mgl)) +
geom_histogram() #Maybe we do not log transform this one, but I will use what yall use

#Salinity
ggplot(NA_Combined, aes(x = Sal_ppt)) +
geom_histogram() 

ggplot(Log_Combined, aes(x = Log_Sal_ppt)) +
geom_histogram() #Almost seems better, but I'll check with yall

#DO
ggplot(NA_Combined, aes(x = DO_mgL)) +
geom_histogram() 

ggplot(Log_Combined, aes(x = log10(DO_mgL))) +
geom_histogram() #Ok definitely using normal one

#pH
ggplot(NA_Combined, aes(x = pH)) +
geom_histogram() #Beautiful

#Season (Thank you Nicole)
ggplot(NA_Combined, aes(x = Season)) +
geom_histogram(stat="count") 

#TSS
ggplot(NA_Combined, aes(x = TSS_mgL)) +
geom_histogram() #Positively skewed

ggplot(Log_Combined, aes(x = Log_TSS_mgL)) +
geom_histogram() #Yay

#Total N
ggplot(NA_Combined, aes(x = Unfiltered_TN_ugL)) +
geom_histogram() 

ggplot(Log_Combined, aes(x = Log_Unfiltered_TN_ugL)) +
geom_histogram()






```

#Correlations

```{r Relationships}

#Temp
ggplot(Log_Combined, aes(x = Temp_C, y = Log_Unfiltered_TN_ugL)) +
geom_point()

#Specific Conductivity
ggplot(Log_Combined, aes(x = Log_SpCond_mScm, y = Log_Unfiltered_TN_ugL)) +
geom_point()

#Conductivity
ggplot(Log_Combined, aes(x = Log_Cond_mScm, y = Log_Unfiltered_TN_ugL)) +
geom_point()

#TDS
ggplot(Log_Combined, aes(x = Log_TDS_mgl, y = Log_Unfiltered_TN_ugL)) +
geom_point() #I don't like this one

#Salinity
ggplot(Log_Combined, aes(x = Log_Sal_ppt, y = Log_Unfiltered_TN_ugL)) +
geom_point() #I don't think salinity is continuous

#DO
ggplot(Log_Combined, aes(x = DO_mgL, y = Log_Unfiltered_TN_ugL)) +
geom_point() 

#pH
ggplot(Log_Combined, aes(x = pH, y = Log_Unfiltered_TN_ugL)) +
geom_point() 

#Season
ggplot(Log_Combined, aes(x = Season, y = Log_Unfiltered_TN_ugL)) +
geom_point() 

#TSS
ggplot(Log_Combined, aes(x = Log_TSS_mgL, y = Log_Unfiltered_TN_ugL)) +
geom_point() 






```

```{r Cor Tests}
#Temp
cor.test(Log_Combined$Temp_C,Log_Combined$Log_SpCond_mScm) #-0.226
cor.test(Log_Combined$Temp_C,Log_Combined$Log_Cond_mScm) #0.015
cor.test #To be continued

#Spec Cond
cor.test(Log_Combined$Log_SpCond_mScm,Log_Combined$Log_Cond_mScm) #0.94 !!!
cor.test(Log_Combined$Log_SpCond_mScm,Log_Combined$Log_TDS_mgl) #0.326
cor.test(Log_Combined$Log_SpCond_mScm,Log_Combined$Log_Sal_ppt) #0.969 !!!
cor.test(Log_Combined$Log_SpCond_mScm,Log_Combined$DO_mgL) #0.335
cor.test(Log_Combined$Log_SpCond_mScm,Log_Combined$pH) #0.161
cor.test(Log_Combined$Log_SpCond_mScm,Log_Combined$Season) #Must be numeric
cor.test(Log_Combined$Log_SpCond_mScm,Log_Combined$Log_TSS_mgL)#-0.406

#Conductivity
cor.test(Log_Combined$Log_Cond_mScm,Log_Combined$Log_TDS_mgl) #0.316
cor.test(Log_Combined$Log_Cond_mScm,Log_Combined$Log_Sal_ppt) #0.934 !!!
cor.test(Log_Combined$Log_Cond_mScm,Log_Combined$DO_mgL) #0.198
cor.test(Log_Combined$Log_Cond_mScm,Log_Combined$pH) #0.195
cor.test(Log_Combined$Log_Cond_mScm,Log_Combined$Log_TSS_mgL) #-0.383

#TDS
cor.test(Log_Combined$Log_TDS_mgl,Log_Combined$Log_Sal_ppt) #0.331
cor.test(Log_Combined$Log_TDS_mgl,Log_Combined$DO_mgL) #0.142
cor.test(Log_Combined$Log_TDS_mgl,Log_Combined$pH) #0.068
cor.test(Log_Combined$Log_TDS_mgl,Log_Combined$Log_TSS_mgL) #-0.150

#Salinity
cor.test(Log_Combined$Log_Sal_ppt,Log_Combined$DO_mgL) #0.323
cor.test(Log_Combined$Log_Sal_ppt,Log_Combined$pH) #0.167
cor.test(Log_Combined$Log_Sal_ppt,Log_Combined$Log_TSS_mgL) #-0.417

#DO
cor.test(Log_Combined$DO_mgL,Log_Combined$pH) #0.095
cor.test(Log_Combined$DO_mgL,Log_Combined$Log_TSS_mgL) #-0.292

#pH
cor.test(Log_Combined$pH,Log_Combined$Log_TSS_mgL) #-0.131









```


